#!/bin/bash

# KSCT - Kamuriki Screen Colour Temperature Config Tool
# Copyright (c) 2023-2024, Nakamura Musical Industries.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of
#    conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice, this list
#    of conditions and the following disclaimer in the documentation and/or other
#    materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its contributors may be
#    used to endorse or promote products derived from this software without specific prior
#    written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

locale=$(localectl | grep -oP '(?<=LANG\=).+')
if [[ ${locale} == "ja_JP.UTF-8" ]]; then
	text="画面の色温度を選んで下さい。"
	column1="温度"
	column2="レベル"
	msg_warmest="アチアチ"
	msg_coldest="ヒエヒエ"
	msg_def="標準"
else
	text="Select the screen colour temperature."
	column1="Temp."
	column2="Level"
	msg_warmest="warmest"
	msg_coldest="coldest"
	msg_def="default"
fi

tmpr=$(zenity --list --title="KSCT" \
	      --text="${text}" \
	      --column="${column1}" --column="${column2}" \
	      700 "0 - ${msg_warmest}" 1400 1 2100 2 2800 3 3500 4 4200 "5 - ${msg_def}" 4900 6 5600 7 6300 8 7000 9 7700 "10 - ${msg_coldest}")
xsct ${tmpr}

