#!/bin/bash

# KSCT - Kamuriki Screen Colour Temperature Config Tool
# Copyright (c) 2023-2024, Nakamura Musical Industries.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of
#    conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice, this list
#    of conditions and the following disclaimer in the documentation and/or other
#    materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its contributors may be
#    used to endorse or promote products derived from this software without specific prior
#    written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if [[ ${LANG} == "ja_JP.UTF-8" ]]; then
	text1="画面の色温度を選んで下さい。"
	text2="画面の明るさを選んで下さい。"
	column1="温度"
	column2="レベル"
	column3="明るさ"
	msg_warmest="アチアチ"
	msg_coldest="ヒエヒエ"
	msg_def="標準"
	msg_brightest="明るい"
	msg_darkest="暗い"
elif [[ ${LANG} != "ja_JP.UTF-8" ]]; then
	text1="Select the screen colour temperature."
	text2="Select the screen brightness."
	column1="Temp."
	column2="Level"
	column3="Brt."
	msg_warmest="warmest"
	msg_coldest="coldest"
	msg_def="default"
	msg_brightest="brightest"
	msg_darkest="darkest"
fi

temp=$(zenity --list --title="KSCT" \
	      --text="${text1}" \
	      --column="${column1}" --column="${column2}" --hide-column=1 \
	      700 "0 - ${msg_warmest}" 1400 1 2100 2 2800 3 3500 4 4200 "5 - ${msg_def}" 4900 6 5600 7 6300 8 7000 9 7700 "10 - ${msg_coldest}")

brt=$(zenity --list --title="KSCT" \
	      --text="${text2}" \
	      --column="${column3}" --column="${column2}" --hide-column=1 \
	      0.05 "0 - ${msg_darkest}" 0.1 1 0.2 2 0.3 3 0.4 4 0.5 "5 - ${msg_def}" 0.6 6 0.7 7 0.8 8 0.9 9 1.0 "10 - ${msg_brightest}")

xsct ${temp} ${brt}

